### ISSUE TITLE
Request for example of commands for all RESP3 types

### ISSUE THREAD

**Issue by mgravell** [redis/redis-specifications#15]
I'm currently implementing [RESP3](https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md) in a library; I'm paranoid - I don't trust any code that I haven't seen working; it would *really* help if there were well-known ways of reproducing all of the expected types using vanilla redis; for example:

- verbatim string: `latency doctor`
- map: `hgetall`
- set: `smembers`
- push: pub/sub

but: I have *not* yet managed to confirm:

- boolean (tried: `sismember`, returns integer)
- double (tried: `incrbyfloat`, returns bulk string)
- blob error
- big integer
- attribute metadata
- streamed bulk-string types
- streamed aggregates

Are there inbuilt APIs that expose these remaining gaps?

**Comment by itamarhaber** [comment]
@mgravell for simple sanity checks, I recommend the built-in `DEBUG PROTOCOL` (https://github.com/redis/redis/blob/unstable/src/debug.c#L442). Also, mind the new config that disables debug by default !)

**Comment by mgravell** [comment]
That's helpful. Anything that does string/array streaming @itamarhaber ?

**Comment by itamarhaber** [comment]
Nope - although these are in the spec, they were never implemented in Redis to this point.

**Comment by mgravell** [comment]
That's brilliant, thanks. Possibly worth a mention of `debug protocol` on the spec page, but: ta

**Comment by itamarhaber** [comment]
I'm so dumb I should be put in a home. Use Lua Luke:

```
EVAL "return { double = 6.379e-5 }" 0
```

Ref: https://redis.io/docs/manual/programmability/lua-api/#lua-to-resp3-type-conversion
