### ISSUE TITLE
RESP3 pub/sub format: Redis implementations do not match the spec

### ISSUE THREAD

**Issue by agronholm** [redis/redis-specifications#16]
I am implementing a Redis client. The RESP3 spec says that pub/sub data should have 4 elements (for RESP2 pub/sub): "pubsub", "message", <channel name> and <message>. But in reality, the pub/sub data received from an actual Redis server (v6 and v7) contain the last 3 elements only. I tried publishing in several ways:

* From a RESP3 Python client I wrote
* From the official redis-py client
* From `redis-cli`
* From `redis-cli` using the RESP2 protocol mode

Each and every time the received push data was the same: `>3\r\n$7\r\nmessage\r\n$5\r\ndummy\r\n$13\r\nHello, world!\r\n`
My question is thus: is the protocol spec wrong, or do circumstances exist where pub/sub data is actually 4 elements long?

**Comment by itamarhaber** [comment]
Hello @agronholm 

Pub/Sub messages always contain exactly three elements - please see [Pub/Sub's docs](https://redis.io/docs/manual/pubsub/#format-of-pushed-messages).

The example in the RESP3 spec shows a Pub/Sub payload (3 elements) in the Push data type (+1 element).
I hope this makes sense.

**Comment by agronholm** [comment]
Where in the payload I pasted above is the push data type? As I see it, there are 3 elements:

1. `message`: indicates that this is a pub/sub message
2. `dummy`: indicates the channel
3. `Hello, world!`: the actual message

So in what world are there ever 4 elements in a pub/sub message?

**Comment by agronholm** [comment]
The RESP3 spec gives an example with 4 elements, but nothing like that ever comes down the wire.

**Comment by itamarhaber** [comment]
Verified - either the spec or the implementation are wrong :)

**Comment by itamarhaber** [comment]
> break the world

Exactly :/

> update the spec

Probably :?

But there's a real problem now, especially considering https://github.com/redis/redis/pull/11216 and possible other (module?) future pushes.

@oranagra @leibale thoughts?

**Comment by oranagra** [comment]
I agree with @leibale. The documentation attempts to specify how push works, but since it uses a pubsub as an example, it is confusing and we should fix it.

I think that when Salvatore wrote it he intended for the push type of pubsub to be `pubsub`. And that this type will have a sub-type (`message` / `unsubscribe`), but when he implemented it he made them different top-level types. So the push type for a pubsub message is simply `message`.

I don't see a technical problem with this going forward, but I agree the spec is misleading so let's fix it.

**Comment by itamarhaber** [comment]
Agreed - adjust the example and drop the `pubsub` (and `monitor`) refs.

@agronholm as the OP you have the first right of fixing if you wish :)
