### ISSUE TITLE
Is map type unordered?

### ISSUE THREAD

**Issue by leibale** [redis/redis-specifications#6]
Spec suggests encoding json as an example and json is unordered, however it doesn't explicitly states this.

Ordered hash maps would complicate implementation for some languages, like go(map) or python(dict).

copy from https://github.com/antirez/RESP3/issues/30

**Comment by dumblob** [comment]
Let me point out Python `dict` **is specified** as ordered (since Python 3).

**Comment by leibale** [comment]
@dumblob see this comment https://github.com/antirez/RESP3/issues/30#issuecomment-557050925
